config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="d-flex justify-content-between align-items-center p-3 bg-light">
<h1>Simple Airbnb</h1>
<%= link_to "Add flat", new_flat_path, class: "btn btn-primary" %>
</div>
<div class="container">
<h1>All our flats (<%= @flats.count %>)</h1>
<div class="container">
<div class="row row-cols-3">
<% @flats.each do |flat| %>
<div class="col p-3 d-flex flex-column">
  <div class="bg-light">
    <h3><%= flat.name %></h3>
    <p><%= flat.address %></p>
      <div class="d-flex">
        <h6 class="me-2"><i class="fa-solid fa-sterling-sign fa-sm"></i> <%= flat.price_per_night %></h6>
        <h6><i class="fa-solid fa-people-group fa-sm"></i> <%= flat.number_of_guests %></h6>
      </div>
    </div>
  </div>
  <div>
    <%= link_to "More info", flat_path(flat), class:"btn" %>
  </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>